version: 2

sources:
  - name: bronze
    database: nessie_catalog
    description: "Dados brutos de mobilidade e clima do Rio de Janeiro, armazenados no Nessie (Apache Iceberg)."
    tables:
      - name: clima_pluviometria
        description: "Medições de precipitação coletadas em intervalos de tempo variados."
        columns:
          - name: primary_key
            description: "Chave primária criada a partir da coluna id_estacao e da data_medicao. Serve para evitar dados duplicados."
          - name: id_estacao
            description: "Identificador único da estação de monitoramento que registrou a medição."
          - name: acumulado_chuva_15_min
            description: "Acumulado de chuva em 15 minutos."
          - name: acumulado_chuva_1_h
            description: "Acumulado de chuva em 1 hora."
          - name: acumulado_chuva_4_h
            description: "Acumulado de chuva em 4 horas."
          - name: acumulado_chuva_24_h
            description: "Acumulado de chuva em 24 horas."
          - name: acumulado_chuva_96_h
            description: "Acumulado de chuva em 96 horas."
          - name: horario
            description: "Horário no qual foi realizada a medição."
          - name: data_particao
            description: "Data em que foi realizada a medição."

      - name: estacoes_clima
        description: "Cadastro georreferenciado das estações de monitoramento meteorológico."
        columns:
          - name: id_estacao
            description: "Identificador único da estação no banco de dados."
          - name: estacao
            description: "Nome ou designação comum da estação (Ex: Copacabana)."
          - name: latitude
            description: "Coordenada geográfica (latitude) em graus decimais."
          - name: longitude
            description: "Coordenada geográfica (longitude) em graus decimais."
          - name: cota
            description: "Altitude da estação em relação ao nível do mar (metros)."
          - name: x
            description: "Coordenada cartesiana X (UTM)."
          - name: y
            description: "Coordenada cartesiana Y (UTM)."
          - name: endereco
            description: "Endereço físico ou ponto de referência da instalação."
          - name: situacao
            description: "Status operacional atual da estação (Ex: Operante)."
          - name: data_inicio_operacao
            description: "Data e hora de início da operação."
          - name: data_fim_operacao
            description: "Data e hora de encerramento das atividades."
          - name: data_atualizacao
            description: "Data e hora da última atualização cadastral."

      - name: viagens_onibus
        description: "Dados operacionais das viagens realizadas pelos ônibus via GPS."
        columns:
          - name: data
            description: "Data da viagem."
          - name: consorcio
            description: "Consórcio ao qual o serviço pertence."
          - name: tipo_dia
            description: "Categoria do dia (Dia Útil, Sábado, Domingo, etc)."
          - name: id_empresa
            description: "Código identificador da empresa operadora."
          - name: id_veiculo
            description: "Código identificador do veículo [número de ordem]."
          - name: id_viagem
            description: "Código único identificador da viagem."
          - name: servico
            description: "Serviço realizado (identificação do trajeto)."
          - name: shape_id
            description: "Código identificador do trajeto (shape)."
          - name: sentido
            description: "Sentido da linha."
          - name: datetime_partida
            description: "Horário de início da viagem."
          - name: datetime_chegada
            description: "Horário de fim da viagem."
          - name: tempo_viagem
            description: "Tempo aferido da viagem (minutos)."
          - name: distancia_planejada
            description: "Distância do trajeto planejado (km)."
          - name: perc_conformidade_shape
            description: "Percentual de sinais GPS dentro do trajeto planejado."
          - name: perc_conformidade_registros
            description: "Percentual de minutos da viagem com registro de sinal."
          - name: versao_modelo
            description: "Código de controle de versão [SHA do GitHub]."