# profiles.yml
meu_mvp_rio:
  target: dev
  outputs:
    dev:
      type: dremio
      # Endereço do coordinator (se for local no docker network, use o nome do serviço)
      host: dremio
      user: "{{ env_var('DREMIO_USER') }}"
      password: "{{ env_var('DREMIO_PASSWORD') }}"
      port: 31010
      database: nessie_catalog # Seu Source no Dremio
      schema: silver # Schema padrão onde o dbt vai escrever
      threads: 4
      # Software ou Cloud? Se for Nessie, geralmente comporta-se como Software em termos de conexão
      cloud_host: null